# Generated by Django 4.0.4 on 2022-06-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestellsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='artikelbestellung',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='beilage',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bestellung',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangosession',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='gehaltsklasse',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='geschaeftsstelle',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='getraenk',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hauptspeise',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='menue',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mitarbeiter',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='schaerfescala',
            options={'managed': True},
        ),
    ]
